bazaar/Cargo.toml
bazaar/src/lib.rs
bazaar/src/tests.rs

Change type of bazaar items from uint to vec<u8> to support string types

Bazaar pallet change items to vec<u8>

---

primitives/src/common.rs
primitives/src/communities.rs

feature-gate `PalletString`.
* String if std
* Vec<u8> if no_std
This is for more convenient handling of the `CommunityMetadata` type in std environments
Tested in node.

Improve dev experience with `CommunityMetadata`

---

personhood-oracle/Cargo.toml
primitives/Cargo.toml
primitives/src/lib.rs
sybil-gate-template/Cargo.toml
test-utils/Cargo.toml

Feature gate sybil primitives

---

Cargo.lock
Cargo.toml
bazaar/rpc/Cargo.toml
bazaar/rpc/runtime-api/Cargo.toml
bazaar/rpc/runtime-api/src/lib.rs
bazaar/rpc/src/lib.rs
bazaar/src/lib.rs

Bazaar rpc

---

ceremonies/src/tests.rs
communities/rpc/runtime-api/src/lib.rs
communities/rpc/src/lib.rs
communities/src/lib.rs
communities/src/tests.rs
primitives/src/communities.rs

closes #63 
* add communities_getLocations rpc 
* fix dispatchable origin constraints

fix communities api

---

balances/src/lib.rs
ceremonies/src/lib.rs
ceremonies/src/tests.rs
communities/src/lib.rs
personhood-oracle/src/lib.rs
scheduler/src/lib.rs

closes #30 
use enums in ensure macro

introduce error enums

---

primitives/src/communities.rs
primitives/src/lib.rs

`CommunityIdentifier` type improvements

---

Cargo.lock
balances/Cargo.toml
balances/src/lib.rs
balances/src/tests.rs
communities/Cargo.toml
communities/src/benchmarking.rs
communities/src/lib.rs
primitives/src/lib.rs
sybil-gate-template/Cargo.toml
sybil-gate-template/src/lib.rs

[primitives] re-export substrate-fixed and use it everywhere

---

balances/src/lib.rs
balances/src/mock.rs
balances/src/tests.rs
bazaar/src/mock.rs
ceremonies/src/lib.rs
ceremonies/src/mock.rs
ceremonies/src/tests.rs
communities/src/benchmarking.rs
communities/src/lib.rs
communities/src/mock.rs
personhood-oracle/src/mock.rs
personhood-oracle/src/tests.rs
primitives/src/balances.rs
primitives/src/ceremonies.rs
primitives/src/communities.rs
primitives/src/sybil.rs
sybil-gate-template/src/lib.rs
sybil-gate-template/src/mock.rs
test-utils/src/lib.rs

parametrize numerous constants for pallets as to make them more configurable
closes #95

parametrize constants

---

primitives/src/communities.rs

* Closes #108
Tested locally that CI scripts work without any update on the node side.

change CommunityMetadata theme type to `IpfsCid`

---

Cargo.lock
Cargo.toml
ceremonies/rpc/Cargo.toml
ceremonies/rpc/runtime-api/Cargo.toml
ceremonies/rpc/runtime-api/src/lib.rs
ceremonies/rpc/src/lib.rs
ceremonies/src/lib.rs

add get_reputations rpc for
#105 [rpc] account summary queries

[ceremonies] add get_reputations rpc

---

balances/src/lib.rs
balances/src/tests.rs
ceremonies/src/lib.rs

Checked with [subsee](https://github.com/ascjones/subsee) that the metadata did not change, so this should not break anything.

Encointer-balances frame-V2

---

balances/src/lib.rs
bazaar/src/lib.rs
ceremonies/src/lib.rs
ceremonies/src/mock.rs
communities/src/lib.rs
communities/src/mock.rs
communities/src/tests.rs
personhood-oracle/src/lib.rs
personhood-oracle/src/mock.rs
test-utils/src/helpers.rs

There was no diff in the metadata; nothing should break.

migrate encointer-communities to frame v2

---

sybil-gate-template/src/lib.rs
sybil-gate-template/src/tests.rs

Note: Did not check any metadata diff. I think it's too tedious to include the pallet in the parachain again just to test that, and we don't have any code that uses the pallet currently.

migrate sybil-gate-template to frame v2

---

ceremonies/src/lib.rs
ceremonies/src/tests.rs
personhood-oracle/src/lib.rs

Metadata has not changed, nothing should break.

migrate encointer-ceremonies to frame v2

---

ceremonies/src/lib.rs
ceremonies/src/mock.rs
ceremonies/src/tests.rs
communities/src/lib.rs
communities/src/tests.rs
test-utils/src/lib.rs

* Purge inactive communities as required by #107

Purge inactive communities

---

Cargo.lock
Cargo.toml
balances/rpc/Cargo.toml
balances/rpc/runtime-api/Cargo.toml
balances/rpc/runtime-api/src/lib.rs
balances/rpc/src/lib.rs
balances/src/lib.rs

implement #105 [rpc] account summary queries with complexity O(#communities)

Balances RPC

---

balances/rpc/src/lib.rs
primitives/src/balances.rs

needed for encointer-node#161
* PartialEq fix for balances
* fix naming of allBalances rpc
* fix encoding of BalanceEntry

fixes for rpc integration

---

Cargo.lock
balances/Cargo.toml
balances/src/tests.rs
bazaar/Cargo.toml
bazaar/src/tests.rs
ceremonies/Cargo.toml
ceremonies/src/lib.rs
ceremonies/src/tests.rs
communities/Cargo.toml
communities/src/lib.rs
communities/src/tests.rs
primitives/Cargo.toml
primitives/src/ceremonies.rs
scheduler/Cargo.toml
scheduler/src/lib.rs
scheduler/src/tests.rs
test-utils/Cargo.toml
test-utils/src/helpers.rs

closes #130 
* added events and respective tests to assert their deposited
* improved logging

add more events & details

---

ceremonies/src/lib.rs
ceremonies/src/mock.rs
test-utils/src/lib.rs

[ceremonies/#141] make assignment limits runtime constants

---

primitives/src/communities.rs

[communities/#156] rename icons to assets

---

balances/src/mock.rs
bazaar/src/mock.rs
ceremonies/src/lib.rs
ceremonies/src/mock.rs
ceremonies/src/tests.rs
communities/src/lib.rs
communities/src/mock.rs
communities/src/tests.rs
personhood-oracle/src/mock.rs
primitives/src/ceremonies.rs
primitives/src/communities.rs
scheduler/src/lib.rs
scheduler/src/tests.rs
test-utils/src/lib.rs

Sudo less governance

---

ceremonies/assignment/src/lib.rs
ceremonies/src/lib.rs
ceremonies/src/mock.rs
ceremonies/src/tests.rs
personhood-oracle/src/mock.rs

[ceremonies/#149] meetup time offset

---

ceremonies/assignment/src/lib.rs
ceremonies/src/lib.rs
ceremonies/src/tests.rs
primitives/src/ceremonies.rs

Signed meetup offset

---

ceremonies/src/lib.rs
communities/src/lib.rs

helps with getting rid of invaluable history (#118 can be postponed)
* add more events and logging

Purge communityceremony

---

bazaar/src/benchmarking.rs
communities/src/benchmarking.rs
scheduler/src/benchmarking.rs

Benchmarking cleanup

---

ceremonies/src/benchmarking.rs
ceremonies/src/lib.rs
ceremonies/src/tests.rs
ceremonies/src/weights.rs

closes #191 
* fixes hardcoded dummy weight for set_meetup_offset

Add missing storage setters

---

ceremonies/assignment/src/lib.rs
ceremonies/src/tests.rs

fix inverse assignment bug

---

ceremonies/assignment/src/lib.rs
ceremonies/assignment/src/math.rs
ceremonies/src/lib.rs
ceremonies/src/tests.rs

Introduces checked math in the assignment crate

Use checked math in assignment crate

---

ceremonies/src/lib.rs
ceremonies/src/tests.rs

Endorsement after registration

---

ceremonies/src/lib.rs
ceremonies/src/mock.rs
ceremonies/src/tests.rs
communities/src/lib.rs
communities/src/mock.rs
personhood-oracle/src/mock.rs
primitives/src/scheduler.rs
scheduler/src/benchmarking.rs
scheduler/src/lib.rs
scheduler/src/mock.rs
scheduler/src/tests.rs

* Closes #208 
Haha, it took me ages to realize why I need to handle this enum type differently on our client side.

[primitives] change `CeremonyPhase` values to CamelCase

---

ceremonies/rpc/src/lib.rs

Tested with node that it works.

Disable bricked reputation cache

---

ceremonies/src/lib.rs
ceremonies/src/tests.rs

implement registering in attestation phase

---

ceremonies/src/lib.rs
ceremonies/src/tests.rs

#222 should be closed in favor of this one.

mark issuance as completed for failed meetup

---

ceremonies/src/benchmarking.rs
ceremonies/src/lib.rs
ceremonies/src/tests.rs

* Closes #242 
Integrations tests pass locally I will push them as soon as we get clarity on #219 because there i introduce a refactoring of the integration tests

allow anybody to claim and refund fees

---

ceremonies/rpc/runtime-api/src/lib.rs
ceremonies/rpc/src/lib.rs
ceremonies/src/lib.rs
primitives/src/ceremonies.rs

* Closes #218 
* Closes #219
* Closes #220

Fix reputation caching

---

.github/workflows/ci.yml
Cargo.lock
balances-tx-payment/src/balance_conversion.rs
balances/src/lib.rs
balances/src/tests.rs
bazaar/src/lib.rs
ceremonies/assignment/src/lib.rs
ceremonies/assignment/src/math.rs
ceremonies/meetup-validation/src/lib.rs
ceremonies/rpc/src/lib.rs
ceremonies/src/lib.rs
ceremonies/src/tests.rs
communities/rpc/src/lib.rs
communities/rpc/src/tests.rs
communities/src/lib.rs
personhood-oracle/src/lib.rs
primitives/Cargo.toml
primitives/core/src/math.rs
primitives/core/src/random_permutation.rs
primitives/src/balances.rs
primitives/src/bazaar.rs
primitives/src/ceremonies.rs
primitives/src/common.rs
primitives/src/communities.rs
primitives/src/sybil.rs
rpc/src/error.rs
scheduler/src/lib.rs
sybil-gate-template/src/lib.rs
test-utils/src/helpers.rs
test-utils/src/lib.rs

Fix clippy warnings

---

communities/src/lib.rs
communities/src/mock.rs
test-utils/src/lib.rs

add new origin TrustableForNonDestructiveAction

---

ceremonies/assignment/src/lib.rs

rules out a runtime issue for 	https://github.com/encointer/encointer-wallet-flutter/issues/903

add unit test for meetup time

---

bazaar/rpc/src/lib.rs
ceremonies/rpc/src/lib.rs
communities/rpc/src/lib.rs
communities/rpc/src/tests.rs

* Closes https://github.com/encointer/encointer-node/issues/308#event-9053032926

mark rpcs as safe

---

bazaar/rpc/src/lib.rs
primitives/src/bazaar.rs

* Closes #318 
The nice thing is that this is a client update only, so we can deploy this fix without doing a runtime upgrade.

Introduce `Business` type containing controller account and the `BusinessData`

---

balances/src/tests.rs
faucet/src/benchmarking.rs
faucet/src/lib.rs
faucet/src/tests.rs
primitives/src/faucet.rs

faucet bypass whitelist option

---

.github/workflows/ci.yml

GHA: fix deprecation warnings (save-state, set-output, Nodejs12) 

---

balances/src/benchmarking.rs
faucet/src/benchmarking.rs

amounts in the benchmark were too small for ED on normal chain setups

fix benchmark amounts

---

ceremonies/src/migrations.rs

implement storage migration for ceremonies v2 Reputation type

---

primitives/src/ceremonies.rs

tiny fix for a problem that popped up during polkadot-sdk-v1.7.0 in encointer runtime

fix sdk 1.7.0 runtime build

---

Cargo.lock
Cargo.toml
balances-tx-payment/Cargo.toml
balances-tx-payment/rpc/Cargo.toml
balances-tx-payment/rpc/runtime-api/Cargo.toml
balances/Cargo.toml
bazaar/Cargo.toml
bazaar/rpc/Cargo.toml
bazaar/rpc/runtime-api/Cargo.toml
ceremonies/Cargo.toml
ceremonies/assignment/Cargo.toml
ceremonies/meetup-validation/Cargo.toml
ceremonies/rpc/Cargo.toml
ceremonies/rpc/runtime-api/Cargo.toml
communities/Cargo.toml
communities/rpc/Cargo.toml
communities/rpc/runtime-api/Cargo.toml
democracy/Cargo.toml
faucet/Cargo.toml
faucet/src/tests.rs
primitives/Cargo.toml
primitives/core/Cargo.toml
reputation-commitments/Cargo.toml
reputation-commitments/src/tests.rs
rpc/Cargo.toml
scheduler/Cargo.toml
test-utils/Cargo.toml
vouches/Cargo.toml

polkadot-v1.12.0

---

Cargo.lock
Cargo.toml
balances-tx-payment/Cargo.toml
balances-tx-payment/rpc/Cargo.toml
balances-tx-payment/rpc/runtime-api/Cargo.toml
balances/Cargo.toml
bazaar/Cargo.toml
bazaar/rpc/Cargo.toml
bazaar/rpc/runtime-api/Cargo.toml
ceremonies/Cargo.toml
ceremonies/assignment/Cargo.toml
ceremonies/meetup-validation/Cargo.toml
ceremonies/rpc/Cargo.toml
ceremonies/rpc/runtime-api/Cargo.toml
communities/Cargo.toml
communities/rpc/Cargo.toml
communities/rpc/runtime-api/Cargo.toml
democracy/Cargo.toml
faucet/Cargo.toml
primitives/Cargo.toml
primitives/core/Cargo.toml
reputation-commitments/Cargo.toml
rpc/Cargo.toml
scheduler/Cargo.toml
test-utils/Cargo.toml
vouches/Cargo.toml

Released the crates as encointer v12 major version

polkadot v1.13.0
