encointer/pallets

balances/src/lib.rs, bazaar/src/lib.rs, ceremonies/src/lib.rs, communities/src/lib.rs
Put `type Error = Error<T>;` in `decl_module` to have it appear in the node metadata. Closes #22
=> Put `Error<T>` in `decl_module`

Cargo.lock, personhood-oracle/src/lib.rs, personhood-oracle/src/tests.rs, primitives/Cargo.toml, primitives/src/sybil.rs, sybil-gate-template/src/lib.rs, sybil-gate-template/src/tests.rs
rococo-v1 branch successfully performs the sybil demo with this update
=> Update parachain sibling `Multilocation` format

Cargo.lock, balances/Cargo.toml, balances/src/lib.rs, balances/src/mock.rs, balances/src/tests.rs, bazaar/Cargo.toml, bazaar/src/lib.rs, bazaar/src/tests.rs, ceremonies/Cargo.toml, ceremonies/src/lib.rs, ceremonies/src/tests.rs, communities/Cargo.toml, communities/src/lib.rs, communities/src/tests.rs, personhood-oracle/Cargo.toml, primitives/Cargo.toml, primitives/src/balances.rs, primitives/src/bazaar.rs, primitives/src/common.rs, primitives/src/communities.rs, primitives/src/lib.rs, scheduler/Cargo.toml, sybil-gate-template/Cargo.toml, sybil-gate-template/src/tests.rs, test-utils/Cargo.toml, test-utils/src/helpers.rs, test-utils/src/lib.rs
-  Draft implementation of #28 
- extend `new_community` extrinsic to include `CommunityMetadata` and `Demurrage`/`NominalIncome` overrides.
- add sudo calls to override the above settings given in the `new_community` extrinsic
- add generic `register_test_currency` in `test-utils` to remove redundant definitions of it.
- constrain amount of bootstrapers. Closes #14
- some other small fixes.
=> Enable community branding

Cargo.lock, balances/Cargo.toml, balances/src/mock.rs, balances/src/tests.rs, bazaar/Cargo.toml, bazaar/src/mock.rs, bazaar/src/tests.rs, ceremonies/Cargo.toml, ceremonies/src/lib.rs, ceremonies/src/tests.rs, communities/Cargo.toml, communities/src/benchmarking.rs, communities/src/lib.rs, communities/src/tests.rs, personhood-oracle/Cargo.toml, primitives/Cargo.toml, primitives/src/communities.rs, scheduler/Cargo.toml, sybil-gate-template/Cargo.toml, test-utils/Cargo.toml, test-utils/src/helpers.rs, test-utils/src/lib.rs
This PR replaces https://github.com/encointer/pallets/pull/50.
closes #9 
* organize meetup location storage in buckets, addressed by geohash
* reduce minimal distance checks to adjacent buckets
It incorporates all changes discussed in the above PR and adds one more feature:
https://github.com/encointer/pallets/commit/b61b39617e157cfde9026c3bec3e60d225953d77 incorporates the datastructure changes from `communities` (due to geohash) into `ceremonies`. The main problem here was that we can no longer retrieve a simple list of all locations from a community, because there is a layer for geohashes in between. I solved the problem as follows:
1.  Add a function `pub fn get_locations(cid:&CommunityIdentifier) -> Vec<Location>` that uses `iter_prefix_values` on the `Locations` double map in …
=> refactor `new_community` to reduce complexity to O(1) using geohash buckets

ceremonies/src/lib.rs, ceremonies/src/tests.rs, primitives/src/ceremonies.rs
the changes in tests can easily be verified by commenting out the performing the random permutation on the indices (ceremonies/src/lib.rs:487)
=> [ceremonies/#65] generate random meetup indices

Cargo.lock, primitives/Cargo.toml, primitives/core/Cargo.toml, primitives/core/src/lib.rs, primitives/core/src/serde.rs, primitives/src/communities.rs
See pr: https://github.com/encointer/encointer-js/pull/29
And discussion in https://github.com/polkadot-js/api/issues/4283.
Tested that it works with encointer-js.
=> Make `CommunityIdentifier` serialization compatible with polkadot-js

Cargo.lock, communities/rpc/runtime-api/src/lib.rs, communities/rpc/src/lib.rs, primitives/Cargo.toml, primitives/core/Cargo.toml, primitives/core/src/lib.rs, primitives/core/src/serde.rs, primitives/src/balances.rs, primitives/src/communities.rs, primitives/src/sybil.rs
The approach before was hacky, and enforced specific handling on all other endpoints (encointer-client, encointer-js, etc).
This PR introduces a simple fixed point serialization shim. Tested with encointer-js.
=> Fix location serialization

Cargo.lock, Cargo.toml, ceremonies/Cargo.toml, ceremonies/assignment/Cargo.toml, ceremonies/assignment/src/lib.rs, ceremonies/assignment/src/math.rs, ceremonies/src/lib.rs, ceremonies/src/tests.rs, primitives/src/ceremonies.rs, rust-toolchain.toml
I extracted most of the assignment functions that don't need state-access to a separate crate to re-use them in the encointer-client.
=> Extract assignment logic to separate crate.

balances/src/lib.rs, ceremonies/src/lib.rs, communities/src/lib.rs
Tested that they appear in the metadata now.
=> show pallet parameters as constants in the metadata.

ceremonies/src/lib.rs, ceremonies/src/mock.rs, ceremonies/src/tests.rs
While introducing the parameter types, there was an erroneously introduced parameter.
Randomly found this while chasing a `ProofOutdated` error in the encointer-wallet.
=> [cermonies] fix the purging of the registry

ceremonies/src/lib.rs, ceremonies/src/mock.rs, ceremonies/src/tests.rs
An integer underrun caused an erroneous `ProofOutdated` error when trying to register with a proof of attendance on the app side. (because we increased the reputation lifetime to 337 recently).
Interestingly, the code panics when this happens in the unit tests, whereas nothing was observed when running the node, except for the above `ProofOutdated` error.
**Todo**
* First merge #111
=> [Ceremonies] Fix handling of reputation lifetime.

ceremonies/src/lib.rs, ceremonies/src/tests.rs
#84 Fix assignment when there are not enough locations available
since the participant index (a monotonically increasing counter per community_ceremony) is used for filtration, assignement slots are distributed in fifo order
=> don't return location index, if not assigned

balances/src/tests.rs, bazaar/src/lib.rs, bazaar/src/tests.rs, test-utils/src/helpers.rs
**Note:** The metadata says that the bazaar's storage prefix changed from `Bazaar` to `EncointerBazaar`.
The rest is identical, so this should not break anything.
=> migrate encointer-bazaar to frame v2

ceremonies/src/lib.rs, communities/src/lib.rs, personhood-oracle/src/lib.rs, scheduler/src/lib.rs, scheduler/src/mock.rs, scheduler/src/tests.rs
Metadata changed only in one detail: the error type was `null` because we forgot to put the error type in the `decl_module` before. Now it is defined, which is a good thing. Nothing should break with this.
=> migrate scheduler to frame v2

balances/src/mock.rs, bazaar/src/mock.rs, ceremonies/src/lib.rs, ceremonies/src/mock.rs, ceremonies/src/tests.rs, communities/src/lib.rs, communities/src/mock.rs, communities/src/tests.rs, personhood-oracle/src/mock.rs, scheduler/src/lib.rs, scheduler/src/mock.rs, scheduler/src/tests.rs, test-utils/src/helpers.rs, test-utils/src/lib.rs
* Closes #77 
Changes:
* [communities]:
* Replace `community_master` genesis field with `CommunityMaster` associated type
* Some extrinsics require now `CommunityMaster` origin, which were unpermissioned before
* [scheduler]
* Replace `ceremony_master` genesis field with `CeremonyMaster` associated type
* [ceremonies]
* Remove `ceremonies::grant_reputation` extrinsic
**Note:** has not been tested with the node, but it would require some version bumping there, which would also require a further version bump in the api-client. (yes, again). So I suggest we merge that untested.
=> Council-permissioned communities and ceremony management

Cargo.lock, balances/Cargo.toml, balances/rpc/Cargo.toml, bazaar/Cargo.toml, bazaar/rpc/Cargo.toml, bazaar/src/tests.rs, ceremonies/Cargo.toml, ceremonies/assignment/Cargo.toml, ceremonies/rpc/Cargo.toml, ceremonies/src/tests.rs, communities/Cargo.toml, communities/rpc/Cargo.toml, personhood-oracle/Cargo.toml, primitives/Cargo.toml, primitives/core/Cargo.toml, rust-toolchain.toml, scheduler/Cargo.toml, sybil-gate-template/Cargo.toml, test-utils/Cargo.toml
bump substrate to rev 9a6d706d8db00abb6ba183839ec98ecd9924b1f8
=> bump substrate: sp-runtime, sp-io, sp-core, sp-keyring are now v5.0.0

balances/src/lib.rs
this was necessary as the node build complained about missing `vec`
how could we ensure this wouldn't pass CI next time @clangenb ?
Also, pallets CI doesn't build no-default-features (even if it would, it wouldn't have detected this!)
=> fix node build error because of missing vec

Cargo.lock, balances/Cargo.toml, balances/src/benchmarking.rs, balances/src/lib.rs
benchmarks can be tested without building the node by running
```cargo test --features runtime-benchmarks --manifest-path balances/Cargo.toml -- benchmarking```
from the `pallets` repo root.
=> [balances/#56] benchmark balances pallet

ceremonies/rpc/runtime-api/src/lib.rs, ceremonies/rpc/src/lib.rs, ceremonies/src/lib.rs, primitives/src/ceremonies.rs
The RPC did not return meaningful values before. We could not infer the ceremony index the reputations were valid.
Now the return value has been changed to: `Vec<(CeremonyIndex, CommunityReputation)>`, where `CommunityReputation = { community_identifier, reputation }`.
=> `ceremonies_getReputation` returns now `CeremonyIndex` too

Cargo.lock, bazaar/src/benchmarking.rs, ceremonies/Cargo.toml, ceremonies/src/benchmarking.rs, ceremonies/src/lib.rs, communities/src/benchmarking.rs, primitives/Cargo.toml, primitives/src/ceremonies.rs, test-utils/src/lib.rs
This predominantly contains changes in the ceremonies-benchmark, which had multiple issues:
* `no_std` incompatibility due to crypto usage. This was circumvented by not using the `sp_core::crypto::sr25519` module. Instead, we created our own crypto application keys with `sp-application-crypto`. This approach is taken from [frame-benchmarking](https://github.com/paritytech/substrate/blob/master/frame/benchmarking/src/baseline.rs).
* the node disliked that we played with block numbers, timestamps and `on_finalize` hooks. Updating the phase was simply replaced by a `scheduler::next_phase` call.
* fixed some unrealistic trait bounds and cleaned up the benchmarking in general.
General Changes:
* Fix some no_std stuff.
Tested:
* benchmarks run for all pallets
=> Fixes for node-integration

balances/src/benchmarking.rs, balances/src/lib.rs
When sending `encointer_balances.transfer` from the rust client, the runtime could not decode the tx.
I have no idea, why we used `StaticLookup` in the first place. The normal `balances` pallet does also use standart account id.
=> Fix encointer balances transfer decoding in runtime

balances/src/lib.rs, balances/src/mock.rs, balances/src/tests.rs, test-utils/src/helpers.rs, test-utils/src/lib.rs
Tested with the encointer-node that we can create accounts with an encointer-balance transfer, and that the created account can send extrinsics without having native balance 🥳
=> EncoinerBalance creates accounts if they did not exists before

Cargo.lock, scheduler/Cargo.toml, scheduler/src/lib.rs
when upgrading to full runtime from launch, we experienced a panic because phase durations were initialized to zero
=> fix division by zero panic if phase duration is zero

ceremonies/src/lib.rs, ceremonies/src/mock.rs, ceremonies/src/tests.rs
* Closes https://github.com/encointer/encointer-parachain/issues/138
The issue was simple: The check if cc was issued in cindex-1 was performed at the very beginning of the registration phase. The problem is that the claiming of cc for cindex-1 only happens in this registration phase after the check.
Fixed by checking for cindex-2.
Added tests and events.
Also renamed `get_inactive_communities_works` -> `update_inactivity_counters_works` beacuse `get` suggests side-effect-freeness which is not the case here
=> fix purging of inactive communities

ceremonies/src/lib.rs, ceremonies/src/tests.rs
The purging was untested, and was not done cleanly. This PR fixes the purging of community/-ceremonies and adds a test.
Fixes:
* We essentially had a storage leak: There were residues in the map when we purged the community ceremony before because the default value was set in the clean-up instead of removing the key. This was correct at some point as far as a remember, but it was bricked after substrate introduced the `OptionQuery` and `ValueQuery` parameters. As we did not test this, we did not notice the change in behaviour.
This PR fixes the above and tests purging the community ceremony.
=> [ceremonies] fix purging of a community and community ceremonies

ceremonies/src/benchmarking.rs, ceremonies/src/lib.rs, ceremonies/src/storage_helper.rs, ceremonies/src/tests.rs, ceremonies/src/weights.rs, primitives/src/scheduler.rs
=> Upgrade registrations and unregister

ceremonies/src/lib.rs, ceremonies/src/tests.rs
* Closes #287 
As commented in #287 I think it makes more sense to first burn the reputable newbie tickets and then the bootstrapper newbie tickets.
=> [ceremonies] bootstrappers can also endorse as reputables

ceremonies/src/lib.rs, primitives/src/ceremonies.rs
a few little things that bugged me when reviewing the new endorsement code
I don't think it is good practise to use base types in pallet storage if used in more than one place
=> types and doc cleanup

balances/src/lib.rs, communities/src/benchmarking.rs, communities/src/lib.rs, primitives/src/balances.rs, primitives/src/communities.rs
Fixes potential overflows when computing the demurrage factor, see: 
* https://github.com/encointer/encointer-node/issues/290
* Closes https://github.com/encointer/pallets/pull/297
=> Make demurrage computation sound

Cargo.lock, ceremonies/src/migrations.rs, communities/Cargo.toml, communities/rpc/src/tests.rs, communities/src/lib.rs, communities/src/migrations.rs, primitives/Cargo.toml, primitives/src/common.rs, primitives/src/communities.rs
closes #334 
closes #335 
breaking change! 
includes a storage migration to v2 for the communities pallet
=> added fields AnnouncementSigner and CommunityRules to CommunityMetadata

balances/src/lib.rs, balances/src/mock.rs, balances/src/tests.rs, faucet/src/mock.rs, test-utils/src/lib.rs
closes #333 
* added a unit test that reproduces the issue
* error was: issue() didn't check for account creation to inc_sufficients
consequence:
current mainnet state is dirty. we have two options
1. runtime state migration checking minimal balances on all accounts and recalculating sufficients and providers. Risk: overloading the block
2. lazy dispatchable `check_sufficients` which does the above per account. combined with a script that calls this extrinsic for every account: Risk: none
=> fix sufficients error

ceremonies/assignment/src/lib.rs, ceremonies/src/tests.rs
* Closes https://github.com/encointer/encointer-wallet-flutter/issues/1459
=> fix assignment bug

Cargo.lock, primitives/core/Cargo.toml, primitives/core/src/bip340.rs, primitives/core/src/lib.rs, primitives/src/communities.rs, primitives/src/democracy.rs
Introduce proper struct, so that we can simplify deserialization of the `Bip340` type. Otherwise, we would have had to add a `[u8; 32]` byte array into the spec file.
Edit: Tested that it works with the node.
=> [ep-core] introduce Bip340 struct

Cargo.lock, README.md, balances-tx-payment/Cargo.toml, balances-tx-payment/rpc/Cargo.toml, balances-tx-payment/rpc/runtime-api/Cargo.toml, balances/Cargo.toml, bazaar/Cargo.toml, bazaar/rpc/Cargo.toml, bazaar/rpc/runtime-api/Cargo.toml, ceremonies/Cargo.toml, ceremonies/assignment/Cargo.toml, ceremonies/meetup-validation/Cargo.toml, ceremonies/rpc/Cargo.toml, ceremonies/rpc/runtime-api/Cargo.toml, communities/Cargo.toml, communities/rpc/Cargo.toml, communities/rpc/runtime-api/Cargo.toml, democracy/Cargo.toml, faucet/Cargo.toml, primitives/Cargo.toml, primitives/core/Cargo.toml, reputation-commitments/Cargo.toml, rpc/Cargo.toml, scheduler/Cargo.toml, test-utils/Cargo.toml, vouches/Cargo.toml
bumping all dependencies to polkadot-v1.2.0
bumping crate versions unified to "2.0.0"
* we must prevent that older node builds accidentally update to higher polkadot dependencies. that will make every polkadot update a breaking change and major version bump
published like that with commands in readme
=> polkadot v1.2.0

ceremonies/src/lib.rs, ceremonies/src/tests.rs, primitives/src/ceremonies.rs
I just implemented this because I wanted to verify my dart proof of attendances in a simple unit test here. (Hint: dart already correctly signs proof of attendances ;))
=> Implement sign and signature verification on `ProofOfAttendance`

Cargo.lock, communities/src/lib.rs, democracy/Cargo.toml, democracy/src/benchmarking.rs, democracy/src/lib.rs, democracy/src/mock.rs, democracy/src/tests.rs, primitives/src/democracy.rs, scheduler/src/lib.rs
Implements pallet side tasks of #347
=> Democracy 2nd iteration

ceremonies/src/migrations.rs, ceremonies/src/mock.rs, ceremonies/src/tests.rs, communities/src/migrations.rs, communities/src/mock.rs, test-utils/src/lib.rs
This is the simulation I ran on the meetup sizes with the new target:
=> Adjust MeetupSizeTarget to 15

Cargo.lock, Cargo.toml, balances-tx-payment/Cargo.toml, balances-tx-payment/rpc/Cargo.toml, balances-tx-payment/rpc/runtime-api/Cargo.toml, balances-tx-payment/rpc/src/lib.rs, balances/Cargo.toml, bazaar/Cargo.toml, bazaar/rpc/Cargo.toml, bazaar/rpc/runtime-api/Cargo.toml, ceremonies/Cargo.toml, ceremonies/assignment/Cargo.toml, ceremonies/meetup-validation/Cargo.toml, ceremonies/rpc/Cargo.toml, ceremonies/rpc/runtime-api/Cargo.toml, communities/Cargo.toml, communities/rpc/Cargo.toml, communities/rpc/runtime-api/Cargo.toml, democracy/Cargo.toml, faucet/Cargo.toml, primitives/Cargo.toml, primitives/core/Cargo.toml, reputation-commitments/Cargo.toml, rpc/Cargo.toml, rpc/src/error.rs, scheduler/Cargo.toml, test-utils/Cargo.toml, test-utils/src/lib.rs, vouches/Cargo.toml
nothing out of the ordinary
release as 6.0.0 to crates.io
=> Ab/polkadot v1.7.0

ceremonies/src/benchmarking.rs, ceremonies/src/lib.rs, ceremonies/src/tests.rs, democracy/src/tests.rs, primitives/src/ceremonies.rs, primitives/src/scheduler.rs
closes #365 
breaking change of reputation enum. needs state migration and adjustments in wallet and rpc
I don't see how the breaking change could be avoided: On the one hand, we want to tolerate noshows (reusing Reputation::VerifiedLinked for a later cycle), on the other hand, we don't want to allow reusing reputation to register several accounts for the same cycles (reusing Reputation::VerifiedLinked for the same cycle)
The only computationally efficient (lazy) way of matching both requirements is by wrapping the cindex in VerifiedLinked variant
_remark:_ I did consider wrapping a `u8` instead of `CeremonyIndexType = u32` and just apply modulo `% 256` to reduce state bloat. As long as ReputationLifetime is < 256, that would still be unambiguous. I decided to go for lower complexity and …
=> tolerate noshows without loss of reputation

ceremonies/src/lib.rs, ceremonies/src/tests.rs
closes #374 
closes #367 
* bootstrappers can no longer use their ProofOfAttendance to register a fresh account as this is a vulnerability
* upon unregistering, reputation is restored for bootstrappers too now
=> protect bootstrapper reputation

democracy/src/lib.rs, democracy/src/mock.rs
I had completely forgotten how democracy works, so I tried to understand it by looking at the code. When I did that I found that I can improve some things along the way.
=> Improve code-quality and doc for democracy pallet

Cargo.lock, Cargo.toml, ceremonies/src/lib.rs
When I submitted our encointer-kusama-runtime PR to the fellowship repo, I noticed that we introduce this old dependency.
=> bump crc dependency to 3.2.1

Cargo.lock, communities/src/lib.rs, democracy/Cargo.toml, democracy/src/lib.rs, democracy/src/migrations.rs, democracy/src/mock.rs, democracy/src/tests.rs, primitives/Cargo.toml, primitives/src/democracy.rs, test-utils/src/lib.rs
closes #393 
closes #392 
closes #391 
closes #390 
* needs storage migration
* will allow very lazy update: a proposal with fulfilled confirming phase will be scheduled for enactment even if update is called after its lifetime ended - unless it has been superseded
=> [democracy] several fixes and enhancements

Cargo.lock, Cargo.toml, balances-tx-payment/Cargo.toml, balances-tx-payment/rpc/Cargo.toml, balances-tx-payment/rpc/runtime-api/Cargo.toml, balances/Cargo.toml, bazaar/Cargo.toml, bazaar/rpc/Cargo.toml, bazaar/rpc/runtime-api/Cargo.toml, ceremonies/Cargo.toml, ceremonies/assignment/Cargo.toml, ceremonies/meetup-validation/Cargo.toml, ceremonies/rpc/Cargo.toml, ceremonies/rpc/runtime-api/Cargo.toml, communities/Cargo.toml, communities/rpc/Cargo.toml, communities/rpc/runtime-api/Cargo.toml, democracy/Cargo.toml, faucet/Cargo.toml, primitives/Cargo.toml, primitives/core/Cargo.toml, reputation-commitments/Cargo.toml, rpc/Cargo.toml, scheduler/Cargo.toml, scheduler/src/lib.rs, test-utils/Cargo.toml, vouches/Cargo.toml
Released as v13 on crates.io and integrated in https://github.com/polkadot-fellows/runtimes/pull/385
=> polkadot-v1.14.0

Cargo.lock, democracy/Cargo.toml, democracy/src/benchmarking.rs
outdated logic about confirmation period in blocks instead of milliseconds needed fixing
=> fix democracy benchmarks

democracy/src/lib.rs
=> fix permill->perthousand

Cargo.lock, Cargo.toml, README.md, balances-tx-payment/Cargo.toml, balances-tx-payment/rpc/Cargo.toml, balances-tx-payment/rpc/runtime-api/Cargo.toml, balances/Cargo.toml, bazaar/Cargo.toml, bazaar/rpc/Cargo.toml, bazaar/rpc/runtime-api/Cargo.toml, ceremonies/Cargo.toml, ceremonies/assignment/Cargo.toml, ceremonies/meetup-validation/Cargo.toml, ceremonies/rpc/Cargo.toml, ceremonies/rpc/runtime-api/Cargo.toml, communities/Cargo.toml, communities/rpc/Cargo.toml, communities/rpc/runtime-api/Cargo.toml, democracy/Cargo.toml, faucet/Cargo.toml, primitives/Cargo.toml, primitives/core/Cargo.toml, reputation-commitments/Cargo.toml, rpc/Cargo.toml, scheduler/Cargo.toml, test-utils/Cargo.toml, treasuries/Cargo.toml, treasuries/rpc/Cargo.toml, treasuries/rpc/runtime-api/Cargo.toml, vouches/Cargo.toml
=> bump to polkadot stable-202409-1 and release encointer as v14

test-utils/src/lib.rs, treasuries/src/lib.rs, treasuries/src/tests.rs
It seems that https://github.com/encointer/encointer-wallet-flutter/issues/1773#issuecomment-2765386660 is coming from the app after all, but we harden the unit tests here by:
* Aligning the test types with the actual runtime types
* Add some more test cases with rs test
=> [treasury] Harden swap native unit tests

.github/workflows/ci.yml, scripts/run_for_all_no_std_crates.sh
This PR fixes and improves the wasm CI. The script was broken such that it only reported an error if the last crate build failed. After this change, it will:
* compile all crates and list an overview of the failed cargo checks at the end.
* Use GA grouping to have foldable sections for each crate for a better log structure
=> Improve wasm CI

Cargo.lock, democracy/Cargo.toml, primitives/Cargo.toml, primitives/src/democracy.rs, treasuries/Cargo.toml, treasuries/src/lib.rs
Closes #433 
Released patch versions for encointer-primitives/democracy/treasuries and the Flow works now.
=> fix get_id for proposal action
